# 单机械臂配置
# 只启用一个机械臂

arms:
  arm1:
    arm_id: zlab_arm
    prefix: ""
    enabled: true
    dof: 6
    base_xyz: [0.0, 0.0, 0.0]
    base_rpy: [0.0, 0.0, 0.0]
    payload_kg: 5  


  arm2:
    arm_id: zlab_arm_right
    prefix: r_
    enabled: false
    dof: 6
    base_xyz: [0.0, 0.8, 0.0]
    base_rpy: [0.0, 0.0, 0.0]
    payload_kg: 5


# 关节限制配置
joint_limits:
  soft_limits_scale: 0.95
  default_velocity_limit: 1.57
  default_acceleration_limit: 3.14

# URDF生成参数
urdf_generation:
  include_visual_meshes: true
  include_collision_meshes: true
  mesh_simplification: medium