# Default initial positions for zlab_robot_single_arm's ros2_control fake system

initial_positions:
  zlab_arm_j1: 0
  zlab_arm_j2: 0
  zlab_arm_j3: 0
  zlab_arm_j4: 0
  zlab_arm_j5: 0
  zlab_arm_j6: 0