# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    zlab_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

zlab_arm_controller:
  ros__parameters:
    joints:
      - zlab_arm_j1
      - zlab_arm_j2
      - zlab_arm_j3
      - zlab_arm_j4
      - zlab_arm_j5
      - zlab_arm_j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true