# Default initial positions for zlab_robot's ros2_control fake system

initial_positions:
  l_j1: 0
  l_j2: 0
  l_j3: 0
  l_j4: 0
  l_j5: 0
  l_j6: 0
  r_j1: 0
  r_j2: 0
  r_j3: 0
  r_j4: 0
  r_j5: 0
  r_j6: 0