# Cartesian limits for Pilz Industrial Motion Planner
cartesian_limits:
  max_trans_vel: 1.0  # m/s
  max_trans_acc: 2.25 # m/s^2
  max_trans_dec: -5.0 # m/s^2
  max_rot_vel: 1.57   # rad/s (90 deg/s)
